### ISSUE TITLE
Add development notes to readme

### ISSUE THREAD

**Issue by matro** [X1011/git-directory-deploy#22]
I've been kind of just winging it so far. Would it be worth adding a "development" section to the readme

Things like...

 * "fork & edit & open a pull request" is :+1: for this project (it isn't always)
 * rebase (or merge?) master before opening a PR, if it matters
 * to squash or not squash commits?

...might be nice to just lay out for folks. Tons of ways to use Git and Github.

**Comment by matro** [comment]
This'd be a good place to put notes about testing, as well. At least when test coverage to the point where it's required for new code. Took me a little groping around to get myself to  https://github.com/sstephenson/bats.

**Comment by matro** [comment]
@X1011 I'd be happy to take a crack this as well, if you're game. Just gotta know your preferences.

**Comment by X1011** [comment]
@matro awesome. I'm gonna say :+1:, merge, and keep commits; I like to preserve history, because it tells the story of how things got to be how they are. And yea, a note on how to run the tests would be good.

Sorry if I haven't been much help; I haven't had much time for coding the past couple days.

**Comment by matro** [comment]
@X1011 No worries at all :-) .
