### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by sergeylukin** [X1011/git-directory-deploy#9]
Just FYI here I described once how to accomplish very similar task using simple series of commands: https://github.com/docpad/docpad/issues/385#issuecomment-13335390

Sorry if that's not what your script intends to do.

**Comment by MoOx** [comment]
You do not keep history of the gh-branch.

**Comment by sergeylukin** [comment]
Sure, I don't. What may be the reason behind keeping history of compiled files while there is history of source files? Just wondering.

**Comment by MoOx** [comment]
just in case for a quick rollback ?

**Comment by sergeylukin** [comment]
We can just prepend a command that backs up the latest state `mv ./out ./out.bak` and then rolling back becomes a matter of running similar series of commands but for `./out_bak` as a base directory.

While I agree that it hardly provides more than 1 restore point, I personally never really needed to rollback more than one build ago. Did you?

**Comment by X1011** [comment]
hi @sergeylukin, thanks for the tip. I have actually seen the force push method before, but I wanted full traceability of changes to the generated files and links back to the source commits they came from, so I could debug any issues caused by the build process, even if there had been multiple deployments in the meantime.

My script also includes several additional features that are useful for CI servers, such as:
- making sure the git username and email are set
- avoiding unnecessary deploys when the generated files do not change
- safeguard to avoid deploying an empty directory
- verbose mode for debugging

**Comment by sergeylukin** [comment]
Thanks for thorough explanation, @X1011 I can see value in features you mentioned. Just wanted to share another solution with you. Cheers
